<?php

    const QCUBED_PROJECT_MODELCONNECTOR_DIR = QCUBED_PROJECT_INCLUDES_DIR . '/connector';
    const QCUBED_PROJECT_MODELCONNECTOR_GEN_DIR = QCUBED_PROJECT_GEN_DIR . '/connector_base';
    const QCUBED_PROJECT_DIALOG_DIR = QCUBED_PROJECT_INCLUDES_DIR . '/dialog';
    const QCUBED_PROJECT_DIALOG_GEN_DIR = QCUBED_PROJECT_GEN_DIR . '/dialog_base';
    const QCUBED_PROJECT_PANEL_DIR = QCUBED_PROJECT_INCLUDES_DIR . '/panel';
    const QCUBED_PROJECT_PANEL_GEN_DIR = QCUBED_PROJECT_GEN_DIR . '/panel_base';
