<?php

use QCubed\Exception\Caller;
use QCubed\Exception\InvalidCast;
use QCubed\Project\Control\DataGrid;
use QCubed\Project\Control\FormBase;
use QCubed\QString;

require_once('../qcubed.inc.php');

class PluginManagerForm extends FormBase
{
    protected DataGrid $dtgPlugins;

    /**
     * @throws Caller
     * @throws InvalidCast
     */
    protected function formCreate(): void
    {
        $this->dtgPlugins_Create();
    }

    /**
     * Creates and initializes the plugin data grid.
     *
     * This method sets up the data grid with specific columns and configurations
     * for displaying plugin information such as name, description, and examples.
     * If the required composer 'installed.json' file is missing, a warning message
     * is set on the data grid.
     *
     * @return void
     * @throws Caller
     * @throws InvalidCast
     */
    private function dtgPlugins_Create(): void
    {
        $this->dtgPlugins = new DataGrid($this, 'dtgPlugins');
        $this->dtgPlugins->setDataBinder('dtgPlugins_Bind');

        $this->dtgPlugins->CssClass = 'datagrid';

        $this->dtgPlugins->createIndexedColumn(t('Name'), 'Name');
        $this->dtgPlugins->createIndexedColumn(t('Description'), 'Description');
        $col = $this->dtgPlugins->createCallableColumn(t('Examples'), [$this, 'renderExampleLink']);
        $col->HtmlEntities = false;

        if (!file_exists(dirname(QCUBED_BASE_DIR) . "/composer/installed.json")) {
            $this->dtgPlugins->Warning = "Could not find the composer 'installed.json' file.";
        }
    }

    /**
     * Binds a data source to the dtgPlugins control with information about installed QCubed-4 libraries.
     *
     * This method reads the `installed.json` file generated by Composer to identify QCubed-4 libraries.
     * It then processes their respective `composer.json` files to extract details such as name, description,
     * and available examples. The extracted data is assigned to the `DataSource` property of the `dtgPlugins` control.
     *
     * @return void This method does not return a value.
     */
    public function dtgPlugins_Bind(): void
    {
        if (!file_exists(dirname(QCUBED_BASE_DIR) . "/composer/installed.json")) {
            return;
        }

        $string = file_get_contents(dirname(QCUBED_BASE_DIR) . "/composer/installed.json");
        $installed = json_decode($string, true);
        $offset = $installed['packages'];
        $qcubed = array_filter($offset,
            function($item) {
                return (!empty($item['type']) && $item['type'] == "qcubed-library");
            });

        $itemArray = [];
        foreach ($qcubed as $item) {
            $strComposerFilePath = dirname(QCUBED_BASE_DIR) . '/' . $item['name'] . '/' . 'composer.json';
            if (file_exists($strComposerFilePath)) {
                $composerDetails = json_decode(file_get_contents($strComposerFilePath), true);

                $arrayItem['Name'] = $item['name'];
                $arrayItem['Description'] = '';
                if (!empty($composerDetails['description'])) {
                    $arrayItem['Description'] = $composerDetails['description'];
                }
                $arrayItem['Examples'] = null;
                if (!empty($composerDetails['extra']['examples'])) { // embed an example page name into a composer file for convenience
                    foreach ($composerDetails['extra']['examples'] as $strExample) {
                        $strExamplePath = dirname(QCUBED_BASE_DIR) . '/' . $item['name'] . '/examples/' . $strExample;
                        if (file_exists($strExamplePath)) {
                            $arrayItem['Examples'][] = $strExample;
                        }
                    }
                }
                $itemArray[] = $arrayItem;
            }
        }
        $this->dtgPlugins->DataSource = $itemArray;
    }

    /**
     * Generates and returns an example link for a given item if examples are available.
     *
     * @param array $item An associative array containing item details, including an 'Examples' key with example links.
     * @return string|null Returns a string containing the generated HTML links for examples, or null if no examples are available.
     */
    public function renderExampleLink(array $item): ?string
    {
        if ($item['Examples']) {
            $strRet = '';
            foreach ($item['Examples'] as $strItem) {
                $strRet .= '<a href="' . dirname(QCUBED_BASE_URL) . '/' . $item['Name'] . '/examples/' . $strItem .
                    '">' . QString::htmlEntities($strItem) . '</a><br />';
            }
            return $strRet;
        }
        return null;
    }
}

PluginManagerForm::run('PluginManagerForm');